networks:
  traefik:
    external: true
  trupesound-internal:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trupe-sound-frontend
    restart: unless-stopped
    networks:
      - traefik
      - trupesound-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trupesound.rule=Host(`trupesound.foguinhodogoias.com`)"
      - "traefik.http.routers.trupesound.entrypoints=web-secure"
      - "traefik.http.routers.trupesound.middlewares=trupesound-auth"
      - "traefik.http.services.trupesound.loadbalancer.server.port=80"
      - "traefik.http.routers.trupesound.tls.certresolver=cloudflare"
      - "traefik.http.middlewares.trupesound-auth.basicauth.removeHeader=true"
      - "traefik.http.middlewares.trupesound-auth.basicauth.users=lucoelho:$$2y$$05$$yVDK8eByB5LUO7MnWYHfZuNMfms/QV/aYS4e0Dl.rBTE4yw8DlEe6"
      # how to set a real password:
      # sudo apt-get install apache2-utils
      # htpasswd -Bnb username password | sed -e s/\\$/\\$\\$/g
