export const ErrorCodes = Object.freeze({
  INVALID_ID: 'INVALID_ID',
  PLAY_NOT_FOUND: 'PLAY_NOT_FOUND',
  ACT_NOT_FOUND: 'ACT_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  USERNAME_ALREADY_REGISTERED: 'USERNAME_ALREADY_REGISTERED',
  UNAUTHORIZED: 'UNAUTHORIZED',
});
